### PR TITLE
i dont know why what i did changed anything...

### PR DESCRIPTION
**Pull request by MisterD66**
But it was throwing an error and using a seperate line for the strip fixed it

### CODE REVIEW

**Comment by ladyada** [comment]
hi for something that 'shouldnt work' please demonstrate what was not working

**Comment by MisterD66** [comment]
Sorry for my messy pull request. it was quite late yesterday when i got it working, i kept getting an error in that line - while debuging i moved the strip comand in an extra line and the error disapeared - to bad i dont know the full name of the error, but i will try to recreate it soon!

**Review by tannewt — CHANGES_REQUESTED** [review]
These should be equivalent. Please reply with more info if it did expose a bug.

**Comment by jposada202020** [comment]
@MisterD66 Hello :), is this an issue with the library or an improvement to solve a problem that you had. 
If it is a problem could you kindly open an issue where you replicate the failure, that way we could keep track. 
Let me know if this PR is still valid ... thanks :)

**Comment by jposada202020** [comment]
I will close this for now, feel free to open an issue if needed. Thanks

**Pull request closed without merging**
